idf_component_register(
    SRCS
        "main.c"
        "../src/display.c"
        "../src/network.c"
        "../src/watch_ui.c"
        "../src/ui_common.c"
        "../src/ota.c"
        "../src/menu_calendar.c"
        "../src/menu_fitness.c"
        "../src/menu_phone.c"
        "../src/menu_settings.c"
        "../src/menu_wallet.c"
        "../src/menu_weather.c"
        "../src/menu_workout.c"
        "../src/menu_world_time.c"
        "../src/lv_font_digits_92.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_https_ota
        esp_http_client
        mbedtls
        json
)